.. change::
    :tags: bug, asyncio
    :tickets: 10813
    :versions: 1.4.51, 2.0.25

    Fixed critical issue in asyncio version of the connection pool where
    calling :meth:`_asyncio.AsyncEngine.dispose` would produce a new connection
    pool that did not fully re-establish the use of asyncio-compatible mutexes,
    leading to the use of a plain ``threading.Lock()`` which would then cause
    deadlocks in an asyncio context when using concurrency features like
    ``asyncio.gather()``.
